apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-reviews
  labels:
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: product-reviews
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: globex
        app.kubernetes.io/name: product-reviews
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: product-reviews
      containers:
        - name: product-reviews
          image: 'quay.io/cloud-architecture-workshop/activity-tracking-service:latest'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /deployments/config
              name: config
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          secret:
            secretName: product-reviews
