apiVersion: v1
kind: Secret
metadata:
  name: product-reviews
  labels:
    app.kubernetes.io/instance: globex
    app.kubernetes.io/name: product-reviews
type: "Opaque"
stringData:
  application.properties: |-
    mp.messaging.outgoing.product-reviews.bootstrap.servers=kafka-kafka-bootstrap.globex-mw-user1.svc.cluster.local:9092
    mp.messaging.outgoing.product-reviews.topic=globex.reviews
    mp.messaging.connector.smallrye-kafka.security.protocol=SASL_PLAINTEXT
    mp.messaging.connector.smallrye-kafka.sasl.mechanism=SCRAM-SHA-512
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      username="globex" \
      password="globex" ; 
